# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='Рейтинг'),
        ),
    ]
