# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 11:17
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_remove_tag_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like', models.BooleanField(verbose_name='Лайк')),
            ],
            options={
                'verbose_name_plural': 'Оценки пользователей',
                'verbose_name': 'Оценка пользователя',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 23, 11, 17, 15, 62529, tzinfo=utc), verbose_name='Дата Добавления'),
        ),
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='article_picture/%Y/%m/%d', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='author',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2017, 5, 23, 11, 17, 15, 63861, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='register_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 23, 11, 17, 15, 61704, tzinfo=utc), verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт'),
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('like_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Like')),
                ('like_to_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Article', verbose_name='Оцениваемая статья')),
            ],
            options={
                'verbose_name': 'Оценка пользователем статьи',
            },
            bases=('questions.like',),
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('like_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questions.Like')),
                ('like_to_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Comment', verbose_name='Оцениваемый ответ')),
            ],
            options={
                'verbose_name': 'Оценка пользователем комментария',
            },
            bases=('questions.like',),
        ),
        migrations.AddField(
            model_name='like',
            name='like_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.UserProfile', verbose_name='Профиль поставившего лайк'),
        ),
    ]
