# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 11:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_auto_20170523_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=32, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.UserProfile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 23, 11, 27, 23, 894073, tzinfo=utc), verbose_name='Дата Добавления'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='register_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 23, 11, 27, 23, 892981, tzinfo=utc), verbose_name='Дата регистрации'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
