# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 11:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_auto_20170523_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='published_by',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 23, 11, 38, 21, 53965, tzinfo=utc), verbose_name='Дата Добавления'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='register_date',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 23, 11, 38, 21, 52612, tzinfo=utc), verbose_name='Дата регистрации'),
        ),
    ]
